/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class FormQLSV extends javax.swing.JFrame {

    ArrayList<QLSV> listNV = new ArrayList<>();
    ArrayList<String> listImage = new ArrayList<>();
    int index;
    DefaultTableModel model = new DefaultTableModel();
    String pathFile = "";
    /**
     * Creates new form GiaodienQL
     */
    Timer updateTimer;
    int DELAY = 100;

    public FormQLSV() {
        initComponents();
        updateTimer = new Timer(DELAY, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date currentTime = new Date();
                String FormatTimeStr = "hh:mm:ss aa";
                DateFormat formatTime = new SimpleDateFormat(FormatTimeStr);
                String FormattedTimeStr = formatTime.format(currentTime);
                lbldongho.setText(FormattedTimeStr);
            }
        });
        updateTimer.start();
        model = (DefaultTableModel) tblStudents.getModel();
        listNV.add(new QLSV("B20DCCN001", "Nguyễn Duy An", 18, "annddcn14885@ptit.edu.vn"));
        listNV.add(new QLSV("B20DCCN002", "Nguyễn Văn Thịnh", 18, "thinhdtcn15048@ptit.edu.vn"));
        listNV.add(new QLSV("B20DCCN003", "Nguyễn Hoàng Nhi", 18, "nhinhcn15064@ptit.edu.vn"));
        listNV.add(new QLSV("B20DCCN004", "Nguyễn Đạt Văn", 18, "vanndcn15047@ptit.edu.vn"));
        listNV.add(new QLSV("B20DCCN005", "Diệp Ông Đại Quang", 18, "quangdocn15144@ptit.edu.vn"));
        listNV.add(new QLSV("B20DCCN006", "Trần Thanh Tùng", 18, "tungttcn15148@ptit.edu.vn"));
        listNV.add(new QLSV("B20DCCN017", "Trần Tiến Dũng", 18, "dungttcn15157@ptit.edu.vn"));
        listNV.add(new QLSV("B20DCCN010", "Trịnh Hữu Thiện Ân", 18, "anthcn15011@ptit.edu.vn"));
        addTable();
        int vitri = 0;
        display(vitri);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        txttuoi = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        lbldongho = new javax.swing.JLabel();
        btnnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnfind = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        lblAvatar = new javax.swing.JLabel();
        btnAvatar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btncuoi = new javax.swing.JButton();
        btntien = new javax.swing.JButton();
        btnlui = new javax.swing.JButton();
        btndau = new javax.swing.JButton();
        btnRecord = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form QLSV Nhom 10");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Quản Lý Sinh Viên");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 19, -1, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã Sinh Viên");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 94, 83, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ và Tên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 141, 83, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tuổi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 189, 83, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 240, 83, 29));

        txtmanv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtmanv, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 94, 243, 29));

        txthoten.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 142, 243, 29));

        txttuoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txttuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 190, 243, 29));

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 240, 243, 29));

        tblStudents.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Họ và tên", "Tuổi", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 392, 923, 120));

        lbldongho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbldongho.setForeground(java.awt.Color.magenta);
        lbldongho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldongho.setText("00:00:00");
        getContentPane().add(lbldongho, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 136, 59));

        btnnew.setBackground(new java.awt.Color(0, 204, 204));
        btnnew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnew.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\bai tap lon\\BTL_OOP_Nhom10\\src\\icon\\Folder-New-icon.png")); // NOI18N
        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        getContentPane().add(btnnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 187, 103, 35));

        btnsave.setBackground(new java.awt.Color(0, 204, 204));
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\bai tap lon\\BTL_OOP_Nhom10\\src\\icon\\save-icon-5402.png")); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 125, 103, 35));

        btnupdate.setBackground(new java.awt.Color(0, 204, 204));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\bai tap lon\\BTL_OOP_Nhom10\\src\\icon\\refresh.png")); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 253, -1, 35));

        btndelete.setBackground(new java.awt.Color(0, 204, 204));
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\bai tap lon\\BTL_OOP_Nhom10\\src\\icon\\delete-folder-1971631-1673171.png")); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 125, 103, 35));

        btnfind.setBackground(new java.awt.Color(0, 204, 204));
        btnfind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfind.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\bai tap lon\\BTL_OOP_Nhom10\\src\\icon\\5d6eea69216fc703baa30fe760deb138.png")); // NOI18N
        btnfind.setText("Find");
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });
        getContentPane().add(btnfind, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 187, 103, 35));

        btnexit.setBackground(new java.awt.Color(0, 204, 204));
        btnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\bai tap lon\\BTL_OOP_Nhom10\\src\\icon\\6948458_preview.png")); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 253, 103, 35));

        lblAvatar.setForeground(new java.awt.Color(204, 204, 204));
        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAvatar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAvatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 90, 143, 143));

        btnAvatar.setBackground(new java.awt.Color(0, 153, 153));
        btnAvatar.setText("CHọn Ảnh");
        btnAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvatarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 263, -1, -1));

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("143 x 143");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 240, -1, -1));

        btncuoi.setBackground(new java.awt.Color(51, 204, 0));
        btncuoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncuoi.setText(">|");
        btncuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuoiActionPerformed(evt);
            }
        });
        getContentPane().add(btncuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 63, 31));

        btntien.setBackground(new java.awt.Color(51, 204, 0));
        btntien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntien.setText(">>");
        btntien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntienActionPerformed(evt);
            }
        });
        getContentPane().add(btntien, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 63, 31));

        btnlui.setBackground(new java.awt.Color(51, 204, 0));
        btnlui.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlui.setText("<<");
        btnlui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluiActionPerformed(evt);
            }
        });
        getContentPane().add(btnlui, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 63, 31));

        btndau.setBackground(new java.awt.Color(51, 204, 0));
        btndau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndau.setText("|<");
        btndau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndauActionPerformed(evt);
            }
        });
        getContentPane().add(btndau, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 63, 31));

        btnRecord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRecord.setForeground(java.awt.Color.blue);
        getContentPane().add(btnRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 98, 31));

        BackGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\bai tap lon\\BTL_OOP_Nhom10\\src\\icon\\63ad8c86128681.5d909dad4fd8a.jpg")); // NOI18N
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 990, 700));

        getAccessibleContext().setAccessibleDescription("Form QLSV Nhom 10");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        xoatrang();
    }//GEN-LAST:event_btnnewActionPerformed

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        try {
            int row = tblStudents.getSelectedRow();
            if (row >= 0) {
                index = row;
                display(index);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblStudentsMouseClicked

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try {

            String ma = txtmanv.getText();
            String hoten = txthoten.getText();
            String email = txtemail.getText();
            int tuoi = Integer.parseInt(txttuoi.getText());
            

            listNV.add(new QLSV(ma, hoten, tuoi, email));
            listImage.add(pathFile);

            model.addRow(new Object[]{ma, hoten, tuoi, email});
            index = listNV.size() - 1;
            display(index);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi" + e);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

        try {
            if (listNV.isEmpty()) {
                JOptionPane.showMessageDialog(null, "không có gì để xóa");
                return;
            }

            int n = JOptionPane.showConfirmDialog(null, "bạn có muốn xóa không");
            if (n == 0) {
                listNV.remove(index);
                addTable();
                JOptionPane.showMessageDialog(null, "xóa thành công");
            }
            if (listNV.isEmpty()) {
                xoatrang();
            } else {
                index = 0;
                display(index);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi" + e);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        String ma = JOptionPane.showInputDialog("mời bạn nhập mã");
        try {

            boolean kq = false;
            for (QLSV x : listNV) {
                if (x.getManv().equalsIgnoreCase(ma)) {
                    index = listNV.indexOf(x);
                    display(index);
                    kq = true;

                    break;
                }
            }
            if (!kq) {
                JOptionPane.showMessageDialog(null, "Không tìm thấy nhân viên có mã " + ma);
            } else {
                JOptionPane.showMessageDialog(null, "Có nhân viên  " + ma);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi" + e);
        }
    }//GEN-LAST:event_btnfindActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        if (listImage.size() > 0) {
            try {
                int hoi = JOptionPane.showConfirmDialog(null, "Trước khi thoát bạn có muốn lưu dữ liệu không");
                if (hoi == 0) {
                    FileOutputStream fileImage = new FileOutputStream("image.dat");
                    ObjectOutputStream ObImage = new ObjectOutputStream(fileImage);
                    ObImage.writeObject(listImage);
                    ObImage.flush();
                    fileImage.flush();
                    ObImage.close();
                    fileImage.close();
                }
            } catch (Exception e) {}

            if (listNV.size() > 0) {
                try {
                    int hoi = JOptionPane.showConfirmDialog(null, "Trước khi thoát bạn có muốn lưu dữ liệu không");
                    if (hoi == 0) {
                        FileOutputStream fos = new FileOutputStream("thongtin.txt");
                        ObjectOutputStream oos = new ObjectOutputStream(fos);

                        oos.writeObject(listNV);

                        oos.flush();
                        fos.flush();
                        oos.close();
                        fos.close();
                        JOptionPane.showMessageDialog(null, "Ghi thanh cong");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Lỗi: " + e);
                }
                System.exit(0);
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            StringBuilder sb = new StringBuilder();
            QLSV user = new QLSV();
            user.setManv(txtmanv.getText());
            user.setHoten(txthoten.getText());
            user.setTuoi(Integer.parseInt(txttuoi.getText()));
            user.setEmail(txtemail.getText());
            
            index = tblStudents.getSelectedRow();

            if (index == -1) {
                JOptionPane.showMessageDialog(this, "chưa chọn dòng");
            } else {
                listNV.set(index, user);
                listImage.add(pathFile);

                addTable();
                tblStudents.setRowSelectionInterval(index, index);
                JOptionPane.showMessageDialog(this, "user update thành công");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "chưa chọn dòng");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvatarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);//chỉ hiển thị file
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            // lấy đường dẫn file để lưu vào 1 trường trong csdl
            pathFile = file.getAbsolutePath();
            BufferedImage b;
            try {
                b = ImageIO.read(file);
                lblAvatar.setIcon(new ImageIcon(b));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnAvatarActionPerformed

    private void btncuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuoiActionPerformed
        try {
            index = listNV.size() - 1;
            display(index);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi" + e);
        }
    }//GEN-LAST:event_btncuoiActionPerformed

    private void btntienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntienActionPerformed
        try {
            if (index < listNV.size() - 1) {
                index++;
                display(index);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi" + e);
        }
    }//GEN-LAST:event_btntienActionPerformed

    private void btnluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluiActionPerformed
        try {
            if (index > 0) {
                index--;
                display(index);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi" + e);
        }
    }//GEN-LAST:event_btnluiActionPerformed

    private void btndauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndauActionPerformed
        try {
            index = 0;
            display(index);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi" + e);
        }
    }//GEN-LAST:event_btndauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQLSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JButton btnAvatar;
    private javax.swing.JLabel btnRecord;
    private javax.swing.JButton btncuoi;
    private javax.swing.JButton btndau;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnfind;
    private javax.swing.JButton btnlui;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btntien;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txttuoi;
    // End of variables declaration//GEN-END:variables

    private void display(int vitri) {
        txtmanv.setText(listNV.get(vitri).getManv());
        txthoten.setText(listNV.get(vitri).getHoten());
        txtemail.setText(listNV.get(vitri).getEmail());
        txttuoi.setText(listNV.get(vitri).getTuoi() + "");
        
        btnRecord.setText("Record " + (vitri + 1) + " of " + listNV.size());
        tblStudents.setRowSelectionInterval(vitri, vitri);
        //lblAvatar.setIcon(new ImageIcon(listImage.get(index)));
    }

    private void addTable() {
        model.setRowCount(0);
        for (QLSV x : listNV) {
            model.addRow(new Object[]{x.getManv(), x.getHoten(), x.getTuoi(), x.getEmail() });
        }
    }

    private void xoatrang() {
        txtemail.setText("");
        txthoten.setText("");
        
        txtmanv.setText("");
        txttuoi.setText("");
        btnRecord.setText("...");
        lblAvatar.setIcon(null);
        index = -1;
    }
}
